name = "cloudflare-image"
compatibility_date = "2023-12-01"
main = 'src/index.ts'
[vars]
MY_VARIABLE = "production_value"
bucket_url = "YOUR_BUCKET_URL"
[[r2_buckets]]
binding = "MY_IMAGES_BUCKET"
bucket_name = "YOUR_BUCKET_NAME"

[placement]
mode = "smart"

[site]
bucket = "src"